### ISSUE TITLE
Fix links on README

### ISSUE THREAD

**Issue by Peiffap** [JuliaOpt/MutableArithmetics.jl#4]

**Comment by blegat** [comment]
There is something weird going on with Travis and their transition from Github services (which is being deprecated) to Github apps. For this repo, travis seems to want it go to use Github apps.

**Comment by Peiffap** [comment]
What can we do about that?

**Comment by blegat** [comment]
It's fixed, the issue with Travis was that it was on travis-ci.org and not travis-ci.com, the issue with github is that it was publishing from the master branch, not the gh-pages branch: https://help.github.com/en/articles/configuring-a-publishing-source-for-your-github-pages-site

**Comment by Peiffap** [comment]
The link to the "stable" version is still broken, but I suspect this is due to the lack of an actual release of the package?

**Comment by saschatimme** [comment]
Yes, stable is always the latest release
