### ISSUE TITLE
Improve add!(p::APL, q::APL) for corner cases

### ISSUE THREAD

**Issue by Peiffap** [JuliaOpt/MutableArithmetics.jl#5]
In your implementation, you do at line 50:
`p += qel`
so everytime a term in `q` is not in `p`, you will reallocate the entire `p`.
A better alternative would be to keep a list of these terms (it will be sorted as it comes sorted with `q`).
Then if this list is empty, just return `p`.
Otherwise, create a polynomial `s` with this sorted list and sum `p` and `s` the classical way (it was more or less what was done in MomentOpt.jl).
That might be the cause of the slowdown because you end up doing the same as `p + q` but you had to compare a monomials etc.. in `add_impl!` that you don't have to do if you just do `p + q`.

**Comment by saschatimme** [comment]
The issue should be filed in MultivariatePolynomials.jl since this has nothing to do with the interface here.

**Comment by Peiffap** [comment]
Good point, I'll leave it up for now though since MultivariatePolynomials still doesn't have MA as a dependency and it would make no sense to open this issue there already.

**Comment by blegat** [comment]
This was done in https://github.com/JuliaAlgebra/MultivariatePolynomials.jl/pull/124
